project_id = "susqsuhzyxgowsylblvc"

[functions.create-pterodactyl-server]
verify_jwt = true

[functions.suspend-pterodactyl-server]
verify_jwt = true

[functions.get-server-status]
verify_jwt = false

[functions.get-all-servers-status]
verify_jwt = false
