project_id = "susqsuhzyxgowsylblvc"

[functions.create-pterodactyl-server]
verify_jwt = true

[functions.suspend-pterodactyl-server]
verify_jwt = true

[functions.get-server-status]
verify_jwt = false

[functions.get-all-servers-status]
verify_jwt = false

[functions.pterodactyl-webhook]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = true

[functions.sync-pterodactyl-servers]
verify_jwt = true

[functions.stripe-create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-sync-products]
verify_jwt = true

[functions.stripe-customer-portal]
verify_jwt = true
